VERILOG = ../src/ql.v ../src/vram.v ../src/sdram.v \
	  ../src/fx68k/fx68k.v ../src/fx68k/fx68kAlu.v ../src/fx68k/uaddrPla.v \
          ../src/hdmi.v ../src/ps2.v ../src/keyboard.v ../src/acia.v \
          ../src/gamerom.v  ../src/video.v ../src/ram.v \
          ../src/mdv_bram.v \
          ../src/osd/osd.v ../src/osd/spi_osd.v \
          ../src/osd/spi_ram_btn.v ../src/osd/spirw_slave_v.v \
	  ../src/sn76489.v ../src/tone_generator.v \
          ../src/spi_display/lcd_video.v \
          ../src/spi_display/hex_decoder_v.v \
	  ../src/ecp5pll.sv

PIN_DEF = ulx3s_v20.lpf

include ulx3s.mk

